// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds_follows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted_feed_follows AS (
    INSERT INTO feed_follows(user_id, feed_id)
    VALUES ($1, $2)
    ON CONFLICT (user_id, feed_id) DO NOTHING
    RETURNING id, created_at, updated_at, user_id, feed_id
),
picked AS(
    SELECT id, created_at, updated_at, user_id, feed_id FROM inserted_feed_follows
    UNION ALL
    SELECT feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id
    FROM feed_follows
    WHERE NOT EXISTS (SELECT 1 FROM inserted_feed_follows)
        AND feed_follows.user_id = $1 AND feed_follows.feed_id = $2
)
SELECT
    picked.user_id AS follow_user_id,
    picked.feed_id AS follow_feed_id,
    feeds.name AS feed_name,
    users.name AS user_name
FROM picked
INNER JOIN users ON picked.user_id = users.id
INNER JOIN feeds ON picked.feed_id = feeds.id
`

type CreateFeedFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

type CreateFeedFollowRow struct {
	FollowUserID uuid.UUID
	FollowFeedID uuid.UUID
	FeedName     string
	UserName     string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow, arg.UserID, arg.FeedID)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.FollowUserID,
		&i.FollowFeedID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const deletFeedFollowByURL = `-- name: DeletFeedFollowByURL :exec
DELETE FROM feed_follows WHERE feed_follows.user_id = $1 AND feed_follows.feed_id = $2
`

type DeletFeedFollowByURLParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeletFeedFollowByURL(ctx context.Context, arg DeletFeedFollowByURLParams) error {
	_, err := q.db.ExecContext(ctx, deletFeedFollowByURL, arg.UserID, arg.FeedID)
	return err
}

const getAllFeedFollow = `-- name: GetAllFeedFollow :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follows
`

func (q *Queries) GetAllFeedFollow(ctx context.Context) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeedFollow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedFollowForUser = `-- name: GetFeedFollowForUser :many
SELECT
    feed_follows.user_id AS  follow_user_id,
    feed_follows.feed_id AS  follow_feed_id,
    users.name AS user_name,
    feeds.name AS feed_name
FROM feed_follows
INNER JOIN users ON feed_follows.user_id = users.id
INNER JOIN feeds ON feed_follows.feed_id = feeds.id
WHERE feed_follows.user_id = $1
`

type GetFeedFollowForUserRow struct {
	FollowUserID uuid.UUID
	FollowFeedID uuid.UUID
	UserName     string
	FeedName     string
}

func (q *Queries) GetFeedFollowForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowForUserRow
	for rows.Next() {
		var i GetFeedFollowForUserRow
		if err := rows.Scan(
			&i.FollowUserID,
			&i.FollowFeedID,
			&i.UserName,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
